example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import add_wishlist, show_wishlist
from wishlist.views import show_xml 
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id 
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import add_wishlist
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', add_wishlist, name='add_wishlist'),
]
urlpatterns += staticfiles_urlpatterns()

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from django import forms
from wishlist.models import BarangWishlist

class wishlistForm(forms.ModelForm):
    class Meta:
        model = BarangWishlist
        fields= [
            'nama_barang',
            'harga_barang',
            'deskripsi'
        ]

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from wishlist.forms import wishlistForm
from wishlist.models import BarangWishlist
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

...
# Create your views here.'
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Achmad Noval Fahrezi',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
    'nama': 'Achmad Noval Fahrezi',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_AJAX.html", context)

# @csrf_exempt
@login_required(login_url="/wishlist/login/")
def add_wishlist(request):
    if request.method == "POST":
        nama_barang = request.POST.get("nama_barang")
        harga_barang = request.POST.get("harga_barang")
        deskripsi = request.POST.get("deskripsi")
        BarangWishlist.objects.create(
            nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi
        )
        JsonResponse({}, status=200)
    return redirect("wishlist:show_wishlist_ajax")


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) 
            response.set_cookie('last_login', str(datetime.datetime.now())) 
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<nav class="navbar" style="background-color: #20c997">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Nama: {{nama}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'wishlist:logout' %}">Log Out</a>
            </li>
          </ul>
        </div>
    </div>
</nav>
<div class="test">
<!-- <img src="{% static "media/tes.jpg" %}" width="600" height="300" 
alt="home"  -->
/>
</div>

<table class="table table-success table-striped-columns" id="">
    <thead>
    <tr>
        <th scope="col">Nama Barang</th>
        <th scope="col">Harga Barang</th>
        <th scope="col">Deskripsi</th>
    </tr>
    </thead>
    <tbody>
    {% for barang in list_barang %}
    <tr>
        <th scope="row">{{barang.nama_barang}}</th>
        <th scope="row">{{barang.harga_barang}}</th>
        <th scope="row">{{barang.deskripsi}}</th>
    </tr>
    {% endfor %}
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    </tbody>
</table>
<h5>Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}

wishlist/templates/wishlist_AJAX.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<script>
    $(document).ready(function(){
        $.get("{% url 'wishlist:show_json' %}", function(data){
            $.each(data, function(index,value){
                $("#wishlist").append(
                    "<tr><td>" + value.fields.nama_barang + "</td><td>" + value.fields.harga_barang + "</td><td>" + value.fields.deskripsi + "</td></tr>"
                )
            })
        })
    })

    $("#wishlist_form").submit(function (e) {
    e.preventDefault();
    var nama_barang = $("#nama_barang").val();
    var harga_barang = parseInt($("#harga_barang").val());
    var deskripsi = $("#deskripsi").val();
    $.ajax({
    type: "POST",
    url: "{% url 'wishlist:add_wishlist' %}",
    data: {
        nama_barang: nama_barang,
        harga_barang: harga_barang,
        deskripsi: deskripsi,
    },
    success: function (response) {
        $("#table-wishlist").append(
            "<tr><td>" +
            nama_barang +
            "</td><td>" +
            harga_barang +
            "</td><td>" +
            deskripsi +
            "</td></tr>"
        );
    },
    error: function (error) {
        console.log(error);
    },
    });
});
</script>


<nav class="navbar" style="background-color: #20c997">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Nama: {{nama}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'wishlist:logout' %}">Log Out</a>
            </li>
          </ul>
        </div>
    </div>
</nav>

<div class="my-auto w-100 mt-3">
    <div class="d-flex gap-3 mb-3">
      <h5>Nama:</h5>
      <span class="badge bg-secondary"><h6>{{nama}}</h6></span>
    </div>
</div>

<div class="container-fluid d-flex justify-content-center item-align-center gap-5">
    <div class="my-auto mx-auto">
      <h3>Add Wishlist</h3>
      <form method="post" id="wishlist_form">
        {% csrf_token %}
        <div class="mb-3">
          <label for="nama_barang" class="form-label">Nama Barang</label>
          <input
            type="text"
            class="form-control"
            placeholder="Masukkan nama barang"
            name="nama_barang"
            id="nama_barang"
          />
        </div>
        <div class="mb-3">
          <label for="harga_barang" class="form-label">Harga Barang</label>
          <input
            type="text"
            class="form-control"
            placeholder="Masukkan harga barang"
            name="harga_barang"
            id="harga_barang"
          />
        </div>
        <div class="mb-3">
          <label for="deskripsi" class="form-label">Deskripsi</label>
          <input
            type="text"
            class="form-control"
            placeholder="Masukkan deskripsi barang"
            name="deskripsi"
            id="deskripsi"
          />
        </div>
        <button type="submit" class="btn btn-primary mb-3">Submit</button>
      </form>
    </div>
</div>

<table class="table table-success table-striped-columns mb-3" id="wishlist">
    <tr>
        <th scope="col" >Nama Barang</th>
        <th scope="col" >Harga Barang</th>
        <th scope="col" >Deskripsi</th>
    </tr>
</table>

<div class="d-flex justify-content-center">
    <h5>Sesi terakhir login: {{ last_login }}</h5>
</div>

{% endblock content %}